### ISSUE TITLE
Ability to suppress some Bepress URLS from Identifier mapping in profile

### ISSUE THREAD

**Issue by dorevabelfiore-temple** [tulibraries/dplah#157]
Per DPLA, there are too many URLS mapping to Identifier coming across from Bepress. Can we suppress the records with "viewcontent" ? @lfinnigan will provide examples.

**Comment by dorevabelfiore-temple** [comment]
Background from Jefferson Bepress rep:

"I wanted to confirm with you that in our oai_dc metadata prefix we do not have the ability to suppress the full-text URL from appearing as dc:identifier. We do have more flexibility with the qualified Dublin Core prefix and as you can see from this qdc output the thumbnail is not being exported: http://jdc.jefferson.edu/do/oai/?verb=ListRecords&metadataPrefix=qdc&set=publication:tju_dmed_photo_album If DPLA can accept Qualified Dublin Core, then perhaps try a harvest using that. "

Because changing to QDC support might introduce too many variables at this time, we are looking at trying to suppress the extra URLS.

**Comment by lfinnigan** [comment]
Emailed to Kate:
Some examples below of download link strings from TJU. Note the first two, which do not contain the text string "viewcontent". All of the video records throughout all of TJU's collections have a download link that's formatted this way (http://jeffline.jefferson.edu/videos/....).

The next two examples provide the pattern that is shared by the rest of the records that do not contain thumbnails.

I do want to point out just as an FYI that TJU has, I believe, 3 collections where thumbnails are displaying. For those records, the download link is formatted like this with "viewcontent" at the end of the url string:
http://jdc.jefferson.edu/context/tju_dmed_photo_album/article/1000/type/native/viewcontent

But since the last instance of dc:identifier for these also contains the url for the thumbnail, it's fine if these download links get caught up in a "find and strip" function.

-----
Collection  name
Jefferson College of Nursing Commencements
OAI
http://jdc.jefferson.edu/do/oai/?verb=ListRecords&metadataPrefix=oai_dc&set= publication:jcncommencement
Download link example
http://jeffline.jefferson.edu/videos/jdc/commencement/2016jcn/
-----
Collection name
Sidney Kimmel Medical College Commencements
OAI
http://jdc.jefferson.edu/do/oai/?verb=ListRecords&metadataPrefix=oai_dc&set=publication:skmccommencement
Download link example
http://jeffline.jefferson.edu/videos/jdc/commencement/2016skmc/
-----
Collection name
On the anatomy of the breast, by Sir Astley Paston Cooper, 1840
OAI
http://jdc.jefferson.edu/do/oai/?verb=ListRecords&metadataPrefix=oai_dc&set=publication:cooper
Download link example
http://jdc.jefferson.edu/cgi/viewcontent.cgi?article=1007&amp;context=cooper
-----
Collection name
Jefferson Biographies
OAI
http://jdc.jefferson.edu/do/oai/?verb=ListRecords&metadataPrefix=oai_dc&set=publication:jeffbiographies
Download link example
http://jdc.jefferson.edu/cgi/viewcontent.cgi?article=1001&amp;context=jeffbiographies

**Comment by dorevabelfiore-temple** [comment]
Related to #158
Tested Good in DEV

**Comment by dorevabelfiore-temple** [comment]
@bibliotechy  merged an incorrect branch , but he is re-merging to TEST and then PROD
