### ISSUE TITLE
Stripping end of string values in date field between 't' and 'z' inclusive

### ISSUE THREAD

**Issue by EliseTemple** [tulibraries/dplah#60]
Leanne for team - 

"Example: TJU has ISO UTC date values
-- Please strip anything between t and z inclusive for the dc:date field"

[http://libcollab.temple.edu/aggregator-testing/catalog/dplapa:TJU_jpgreenletters_1038]

**Comment by relaxing** [comment]
@bibliotechy   Is the desired time format for all items YYYY-MM-DD?  Should we be converting all incoming timestamps to that format?  Or am I just targeting dates that contain a T and Z?

**Comment by relaxing** [comment]
Actually, never mind. I can already see a number of time fields which don't parse nicely. Examples: "1896/1907",  "1902-02"
Going to restrict this to looking for only iso8601 timestamps and removing the time portion.

**Comment by bibliotechy** [comment]
👍

**Comment by lfinnigan** [comment]
Just to elaborate a bit more on this issue - this normalization would help dates specifically coming from bepress repositories. The output format for all bepress dates is YYYY-MM-DDT##:##:##Z (example: 1861-01-01T07:52:58Z). We just want to be able to lop off the end bits between T and Z inclusive since the actual timestamp is meaningless and unsightly. We don't see this pattern from any other repository.

**Comment by EliseTemple** [comment]
Tested and looks good - Doreva and Leanne
