### ISSUE TITLE
Advise on Structure of Rights Metadata

### ISSUE THREAD

**Issue by EliseTemple** [tulibraries/dplah#84]
If we asked the contributors to supply URIs for their rights statements would the aggregator be able to go to that URI on the Creative Commons or RightsStatements.org & pull the human readable graphical or text representation of that rights statement - or should we ask the contributors to supply both the URI and the human readable equivalent of the rights statement - as well a free text rights statement.

Please advise on possible functionality so that the metadata team can write up guidelines accordingly.

**Comment by bibliotechy** [comment]
Tagging @kelynch to get her opinion on this one as well.

We could certainly parse rights statements URIs and assign the appropriate text and or graphical representation. 

I'd guess we'd prefer to cache them locally rather than grabbing the text them for each record, but the idea is still the same:
 
- they provide a URI 
- we parse and recognize it 
- we fill in the Rights Statement based on the provided URI. 

They would not need to include the rights statement text. In fact, that sounds like a terrible idea. We all know some librarian would want to slightly alter the text of "their" version of the right statement. I think only allowing them to specify the URi means we will always have the canonical text.

**Comment by kelynch** [comment]
Agreed with @bibliotechy on this one.  Allowing folks to specify a URI would be helpful, but if we're going to display the full text of the rights, the canonical text should come from our end (maybe through an API, or in the short-term a Rights class).  

If I'm remembering correctly, recommendations from RightsStatements.org are to provide the human-readable URI to the rights statement on RightsStatements.org, so we would be in line with these recommendations FWIW if we go this route.

**Comment by EliseTemple** [comment]
Spoke to Gretchen G. of DPLA and she will attempt to have straight URI's resolve to rightsstatements.org and creative commons licenses as of new harvest of week of August 29, 2016. Then we can start thinking of future how to address this issue under simple dublin core (Fedora 3) for the short term.

**Comment by dorevabelfiore-temple** [comment]
Gretchen has turned on the URI resolution on the DPLA side. We are marking this as on hold until Spring 2017 when we can better address the DPLA's recommendations.
